package DEMSApp;


/**
* DEMSApp/interfaces.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSApp.idl
* Wednesday, February 26, 2020 6:07:09 PM EST
*/

public interface interfaces extends interfacesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface interfaces
