package DEMSApp;


/**
* DEMSApp/interfacesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSApp.idl
* Wednesday, February 26, 2020 6:07:09 PM EST
*/

public interface interfacesOperations 
{
  String addEvent (String eventID, String eventType, int bookCap);
  String removeEvent (String eventID, String eventType);
  String listEventAvailability (String eventType);
  String getOwnlistEevntAvailability (String eventType);
  String bookEvent (String customerID, String eventID, String eventType);
  String getBookingSchedule (String customerID);
  String cancelEvent (String customerID, String eventID, String eventType);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
  void shutdown ();
} // interface interfacesOperations
