package DEMSApp;


/**
* DEMSApp/interfacesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSApp.idl
* Wednesday, February 26, 2020 6:07:09 PM EST
*/

abstract public class interfacesHelper
{
  private static String  _id = "IDL:DEMSApp/interfaces:1.0";

  public static void insert (org.omg.CORBA.Any a, DEMSApp.interfaces that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DEMSApp.interfaces extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DEMSApp.interfacesHelper.id (), "interfaces");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DEMSApp.interfaces read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_interfacesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DEMSApp.interfaces value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DEMSApp.interfaces narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DEMSApp.interfaces)
      return (DEMSApp.interfaces)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DEMSApp._interfacesStub stub = new DEMSApp._interfacesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DEMSApp.interfaces unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DEMSApp.interfaces)
      return (DEMSApp.interfaces)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DEMSApp._interfacesStub stub = new DEMSApp._interfacesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
