package DEMSApp;

/**
* DEMSApp/interfacesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSApp.idl
* Wednesday, February 26, 2020 6:07:09 PM EST
*/

public final class interfacesHolder implements org.omg.CORBA.portable.Streamable
{
  public DEMSApp.interfaces value = null;

  public interfacesHolder ()
  {
  }

  public interfacesHolder (DEMSApp.interfaces initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DEMSApp.interfacesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DEMSApp.interfacesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DEMSApp.interfacesHelper.type ();
  }

}
